name: Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --release

      - name: Extract version from Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "Release v${{ env.VERSION }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/please-rs.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
